### ISSUE TITLE
Crash in simple_script example

### ISSUE THREAD

**Issue by pzmarzly** [spawnfest/bakeware#36]
On latest `main` commit:

```bash
$ cd bakeware/examples/simple_script
$ mix deps.get
$ MIX_ENV=prod mix release
...
==> simple_script
Compiling 1 file (.ex)
Generated simple_script app
* assembling simple_script-0.1.0 on MIX_ENV=prod
* skipping runtime configuration (config/releases.exs not found)
* skipping elixir.bat for windows (bin/elixir.bat not found in the Elixir installation)
* skipping iex.bat for windows (bin/iex.bat not found in the Elixir installation)
* assembling bakeware simple_script

* warning [Bakeware] zstd not installed. Skipping compression...

Bakeware successfully assembled executable at _build/prod/rel/bakeware/simple_script

Release created at _build/prod/rel/simple_script!

    # To start your system
    _build/prod/rel/simple_script/bin/simple_script start

Once the release is running:

    # To connect to it remotely
    _build/prod/rel/simple_script/bin/simple_script remote

    # To stop it gracefully (you may also send SIGINT/SIGTERM)
    _build/prod/rel/simple_script/bin/simple_script stop

To list all commands:

    _build/prod/rel/simple_script/bin/simple_script
$ _build/prod/rel/simple_script/bin/simple_script start Hi   
warning: Caught exception in main/1: :error => :function_clause
  (elixir 1.10.4) lib/integer.ex:232: Integer.parse(nil, 10)
  (simple_script 0.1.0) lib/bakeware/script.ex:35: SimpleScript._main/0
  (elixir 1.10.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
  (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
$ elixir -v              
Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.10.4 (compiled with Erlang/OTP 22)
```

**Comment by pzmarzly** [comment]
Ok, nvm, I was running the wrong executable (mind the path).

```bash
$ _build/prod/rel/bakeware/simple_script Hi
bakeware: starting '/home/pzmarzly/bakeware/examples/simple_script/_build/prod/rel/bakeware/simple_script' (cachedir=/home/pzmarzly/.cache/bakeware)...
bakeware: Cache invalid. Extracting...
bakeware: Running /home/pzmarzly/.cache/bakeware/ed3458605d948c157c79c4a51d9ff64998ad9a3ed323514b97567ca97a353cd5/start...
Hi
```

**Comment by fhunleth** [comment]
Yes - I agree that it's really easy to make this mistake with the current build output. I added #38 for when we get back to working on this.
